###
// 회원가입
POST http://15.164.210.163:4000/api/signup
Content-Type: application/json

{
  "email":"test123@gooogle.com",
  "nickname":"테스트",
  "password":"qwer12345",
  "confirmPassword": "qwer12345"
}

###
// 로그인
POST http://15.164.210.163:4000/api/login
Content-Type: application/json

{
    "email":"test123@gooogle.com",
    "password":"qwer12345"
}

###
// 중복검사
GET http://127.0.0.1:4000/api/duplicates/email
Content-Type: application/json

{
  "email":"test12345@gooogle.com"
}
###
// 중복검사
GET http://127.0.0.1:4000/api/duplicates/nickname
Content-Type: application/json

{
  "nickname":"테스트"
}



# import axios from "axios"; 
# const TOKEN = localStorage.getItem("token"); 
# const api = axios.create({ // 기본 서버주소 baseURL: "http://pooreum.shop", });

